
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asos-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: asos-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
